### ISSUE TITLE
Does not parse long syntax for volumes

### ISSUE THREAD

**Issue by lordpuma** [dzek69/docker-windows-notifier#1]
Thank you for this amazing software!

Please check out the long syntax in docker-compose file for volumes, [link](https://docs.docker.com/compose/compose-file/#long-syntax-3), at the moment you only parse the short syntax. 

It throws error when you use the long one.
`volume.split is not a function or its return value is not iterable`

**Comment by dzek69** [comment]
Hello,

Thanks for your report, this is fixed now. Update your npm install or head to Releases on GitHub to get 1.1.0 version.
